baseURL = 'https://mariasolos.com/'
languageCode = 'en-us'
title = 'Maria Solano'
enableRobotsTXT = true

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[markup]
    [markup.highlight]
        lineNos = true
        style = 'dracula'

[params]
    [params.author]
        name = 'Maria Solano'
        email = 'majosolano99@gmail.com'

    description = 'Personal website of Maria Solano'
